version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db


  api:
    container_name: api_container
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app  
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: name
    depends_on:
      - mongo_db  

  front:
    container_name: front_container
    build: ./frontend
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    depends_on:
      - api    

  nginx:
    image: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env  
    ports:
      - 9999:9999
     

volumes:
  mongo_db: {}
